default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 50
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: asalnagrik_development